[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  # Comando para levantar Astro en desarrollo
  command = "npm run dev"
  # Puerto donde Astro ya está configurado (ver astro.config.mjs)
  targetPort = 7001

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200